on:
  workflow_dispatch:
    
jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
    - uses: blombard/move-to-next-iteration@v0.6.1
      with:
        owner: jazzcattest
        number: 16
        token: ${{ secrets.PROJECT_PAT }}
        iteration-field: Sprint
        iteration: last
        new-iteration: current
        statuses: 'In Progress'
